name: starguide_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.3.0
  dartantic_ai: ^0.9.7
  json_schema: ^5.2.1
  serverpod: 3.0.0-alpha.3
  serverpod_auth_server: 3.0.0-alpha.3

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 3.0.0-alpha.3

