name: starguide_client
description: The client for connecting to Serverpod's Starguide server.
version: 0.1.2
repository: https://github.com/serverpod/starguide

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod_client: 3.0.0-rc.2
  serverpod_auth_client: 3.0.0-rc.2

