name: starguide_client
description: The client for connecting to Serverpod's Starguide server.
version: 0.1.1
repository: https://github.com/serverpod/starguide

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod_client: 2.9.1

